# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

dist: xenial

# install sf system dependencies
addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libpoppler-cpp-dev

# for codecov
r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'

# deploy package site built via pkgdown
deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition:
        - $TRAVIS_R_VERSION_STRING = release
